version: '3.8'

services:
  developer-hub:
    image: registry.access.redhat.com/rhdh/rhdh-hub-rhel9:latest
    container_name: developer-hub
    entrypoint: ["/usr/src/app/packages/app-config/start_dev_hub.sh"]
    userns_mode: keep-id:uid=1001
    environment:
      - PORT=3001
      - APP_CONFIG=/usr/src/app/packages/app-config/app-config.yaml
      - NODE_TLS_REJECT_UNAUTHORIZED='0'
    volumes:
      - ./dev-hub:/usr/src/app/packages/app-config
    ports:
      - "7007:7007"

volumes:
  config:
  data:
  log:
  registry:
  ssl:
